# Copyright (C) 2011 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/semc/phoenix/setup-makefiles.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES := \
    vendor/semc/phoenix/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so

PRODUCT_COPY_FILES += \
    
vendor/semc/phoenix/proprietarybin/akmd8975
vendor/semc/phoenix/proprietarybin/chargemon
vendor/semc/phoenix/proprietarybin/netmgrd
vendor/semc/phoenix/proprietarybin/port-bridge
vendor/semc/phoenix/proprietarybin/qmuxd
vendor/semc/phoenix/proprietaryetc/firmware/bcm4329.hcd
vendor/semc/phoenix/proprietaryetc/firmware/fw_bcm4329.bin
vendor/semc/phoenix/proprietaryetc/firmware/fw_bcm4329_apsta.bin
vendor/semc/phoenix/proprietaryetc/firmware/leia_pfp_470.fw
vendor/semc/phoenix/proprietaryetc/firmware/leia_pm4_470.fw
vendor/semc/phoenix/proprietaryetc/firmware/ti-connectivity
vendor/semc/phoenix/proprietaryetc/firmware/ti-connectivity/wl1271-nvs.bin
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_command_control.fw
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_h263_dec_mc.fw
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_h264_dec_mc.fw
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_h264_enc_mc.fw
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_mp4_dec_mc.fw
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_mp4_enc_mc.fw
vendor/semc/phoenix/proprietaryetc/firmware/vidc_720p_vc1_dec_mc.fw
vendor/semc/phoenix/proprietaryetc/firmware/yamato_pfp.fw
vendor/semc/phoenix/proprietaryetc/firmware/yamato_pm4.fw
vendor/semc/phoenix/proprietaryetc/permissions/com.sonyericsson.android.xperiaplaycertified.xml
vendor/semc/phoenix/proprietaryetc/wifi/calibration
vendor/semc/phoenix/proprietaryetc/wifi/wpa_supplicant.conf
vendor/semc/phoenix/proprietaryframework/xperiaplaycertified.jar
vendor/semc/phoenix/proprietarylib/egl/egl.cfg
vendor/semc/phoenix/proprietarylib/egl/eglsubAndroid.so
vendor/semc/phoenix/proprietarylib/egl/libEGL_adreno200.so
vendor/semc/phoenix/proprietarylib/egl/libGLESv1_CM_adreno200.so
vendor/semc/phoenix/proprietarylib/egl/libGLESv2_adreno200.so
vendor/semc/phoenix/proprietarylib/egl/libGLES_android.so
vendor/semc/phoenix/proprietarylib/egl/libq3dtools_adreno200.so
vendor/semc/phoenix/proprietarylib/hw/camera.semc.so
vendor/semc/phoenix/proprietarylib/libaudioalsa.so
vendor/semc/phoenix/proprietarylib/libauth.so
vendor/semc/phoenix/proprietarylib/libC2D2.so
vendor/semc/phoenix/proprietarylib/libcm.so
vendor/semc/phoenix/proprietarylib/libdiag.so
vendor/semc/phoenix/proprietarylib/libdl.so
vendor/semc/phoenix/proprietarylib/libdsi_netctrl.so
vendor/semc/phoenix/proprietarylib/libdsm.so
vendor/semc/phoenix/proprietarylib/libdss.so
vendor/semc/phoenix/proprietarylib/libdsutils.so
vendor/semc/phoenix/proprietarylib/libgemini.so
vendor/semc/phoenix/proprietarylib/libgsdi_exp.so
vendor/semc/phoenix/proprietarylib/libgsl.so
vendor/semc/phoenix/proprietarylib/libgstk_exp.so
vendor/semc/phoenix/proprietarylib/libidl.so
vendor/semc/phoenix/proprietarylib/libmiscta.so
vendor/semc/phoenix/proprietarylib/libmmgsdilib.so
vendor/semc/phoenix/proprietarylib/libmmipl.so
vendor/semc/phoenix/proprietarylib/libmmjpeg.so
vendor/semc/phoenix/proprietarylib/libnetmgr.so
vendor/semc/phoenix/proprietarylib/libnv.so
vendor/semc/phoenix/proprietarylib/liboemcamera.so
vendor/semc/phoenix/proprietarylib/liboem_rapi.so
vendor/semc/phoenix/proprietarylib/liboncrpc.so
vendor/semc/phoenix/proprietarylib/libOpenVG.so
vendor/semc/phoenix/proprietarylib/libpbmlib.so
vendor/semc/phoenix/proprietarylib/libqdp.so
vendor/semc/phoenix/proprietarylib/libqmi.so
vendor/semc/phoenix/proprietarylib/libqueue.so
vendor/semc/phoenix/proprietarylib/libril-qc-1.so
vendor/semc/phoenix/proprietarylib/libril.so
vendor/semc/phoenix/proprietarylib/libsc-a2xx.so
vendor/semc/phoenix/proprietarylib/libuim.so
vendor/semc/phoenix/proprietarylib/libwms.so
vendor/semc/phoenix/proprietarylib/libwmsts.so
